name: Lint, test and deploy

on: release

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
        pip install .[dev]
    - name: lint
      run: |
        isort src --check
        pylint src
    - name: mypy
      run: mypy src
    - name: pytest
      run: pytest tests        
    - name: build and upload
      if: ${{ (github.event_name == 'release') && (matrix.os == 'ubuntu-latest') && (matrix.python-version == '3.6') }}
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        GITHUB_REF: ${{ github.ref }}
        DEPLOY: 1
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
        python setup.py sdist bdist_wheel
        twine check dist/*
        twine upload --verbose dist/*
