name: Lint and test on push

on: [push, release]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
        os: [macos-latest, ubuntu-latest, 'windows-latest']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install .[dev]
    - name: lint
      run: |
        isort src --check
        pylint src
    - name: mypy
      run: mypy src
    - name: pytest
      run: pytest tests

  release:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: prep
      env:
        EVENT_NAME: ${{ github.event_name }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        echo $EVENT_NAME
        echo $REF
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: install build tools
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
    - name: build and upload
      if: ${{ github.event_name == 'release' }}
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*
        twine upload --verbose dist/*
