name: Test build

on: push

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - name: prep
      env:
        EVENT_NAME: ${{ github.event_name }}
        REF: ${{ github.ref }}
      run: |
        echo $EVENT_NAME
        echo $REF
    - name: build
      if: ${{ github.event_name == 'push' }}
      run: |
        echo "HEY"